version: 0.2

env:
  variables:
    ENV_NAME: "dev"
    AWS_REGION: "eu-west-3"

phases:
  build:
    commands:
      - aws --version
      - aws cloudformation deploy \
          --region "$AWS_REGION" \
          --stack-name "${ENV_NAME}-network" \
          --template-file infra/network.yaml \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides EnvironmentName="$ENV_NAME"
