version: 0.2

env:
  variables:
    ENV_NAME: "dev"
    AWS_REGION: "eu-west-3"
    ARTIFACT_BUCKET: studiinfra-cfn-artifacts-bucket


phases:
  install:
    commands:
      - aws --version
  build:
    commands:
      - aws cloudformation package
          --region "$AWS_REGION"
          --template-file master.yaml
          --s3-bucket "$ARTIFACT_BUCKET"
          --s3-prefix "cfn/$ENV_NAME"
          --output-template-file master.packaged.yaml


      - aws cloudformation deploy 
        --region "$AWS_REGION" 
        --stack-name "${ENV_NAME}-master" 
        --template-file master.packaged.yaml 
        --capabilities CAPABILITY_NAMED_IAM 
        --parameter-overrides EnvironmentName="$ENV_NAME" 
        --role-arn arn:aws:iam::142706263687:role/cfn-studistoreinfra-exec-role 
        --parameter-overrides EnvironmentName="$ENV_NAME"

artifacts:
  files:
    - master.packaged.yaml
