AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS PostgreSQL (Private)"

Parameters:
  EnvironmentName:
    Type: String

  VpcId:
    Type: AWS::EC2::VPC::Id

  PrivateSubnetIds:
    Type: CommaDelimitedList

  DbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:

  #####################################
  # DB Subnet Group (PRIVATE)
  #####################################
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub "${EnvironmentName} DB subnet group"
      SubnetIds: !Ref PrivateSubnetIds
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-db-subnet-group"

  #####################################
  # Secret (DB credentials)
  #####################################
  DbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${EnvironmentName}/postgres"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  #####################################
  # PostgreSQL Instance (PRIVATE)
  #####################################
  PostgresDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${EnvironmentName}-postgres"
      Engine: postgres
      EngineVersion: "15"
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MultiAZ: false
      StorageType: gp3

      MasterUsername: !Sub "{{resolve:secretsmanager:${DbSecret}:SecretString:username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${DbSecret}:SecretString:password}}"

      DBSubnetGroupName: !Ref DbSubnetGroup
      VPCSecurityGroups:
        - !Ref DbSecurityGroupId

      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      DeletionProtection: false

Outputs:

  DbEndpoint:
    Value: !GetAtt PostgresDB.Endpoint.Address

  DbSecretArn:
    Value: !Ref DbSecret